/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package manejoVentanasEstudiantes;

/**
 *
 * @author Rafa
 */
public class ventanaListarEstudiantes extends java.awt.Dialog {
     private GestorEstudiante gEstudiante;
     int posicion = 0;
     String pos = null;
     int ind;
     int cont =0;
     int nCoincidencias = 0;
    /**
     * Creates new form ventanaListarEstudiantes
     */
    public ventanaListarEstudiantes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
     
  
     public void busqueda(String claveBusqueda) throws ExceptionInInitializerError{
         try{
         for(ind=0; ind<gEstudiante.getEstudiantes().length; ind++){
             if(gEstudiante.getEstudiantes()[ind].getCedula().equals(claveBusqueda)){
                 System.out.println("El usuario con el id buscado es: "+gEstudiante
                         .getEstudiantes()[ind].getNombre()+ " \n");
                 cont++;
                 mostrarCoincidencias();
             }
             if(gEstudiante.getEstudiantes()[ind].getNombre().equals(claveBusqueda)){
                 System.out.println("El usuario con el id buscado es: "+gEstudiante
                         .getEstudiantes()[ind].getApellido()+ " \n");
                 cont++;
             }
             if(gEstudiante.getEstudiantes()[ind].getApellido().equals(claveBusqueda)){
                 cont++;
             }
             else{
                 System.out.println("No se encontraron coincidencias");
             }
         }
         }catch(Exception e) {
             System.out.println("");
         }
     }
     
     private void borrarDatosTabla(){
        int numEstudiantes = gEstudiante.getNumEstudiantes();
        for(int i = 0; i < numEstudiantes; i++){
            this.tabEstudiantes.setValueAt("", i, 0);
            this.tabEstudiantes.setValueAt("", i, 1);
            this.tabEstudiantes.setValueAt("", i, 2);
            this.tabEstudiantes.setValueAt("", i, 3);
            this.tabEstudiantes.setValueAt("", i, 4);
            this.tabEstudiantes.setValueAt("", i, 5);
            this.tabEstudiantes.setValueAt("", i, 6);
            this.tabEstudiantes.setValueAt("", i, 7);
            this.tabEstudiantes.setValueAt("", i, 8);
        }
     }
     
    public void mostrarCoincidencias(){
        int numEstudiantes = gEstudiante.getNumEstudiantes();
        for(int i = 0; i < cont; i++){
            this.tabEstudiantes.setValueAt(gEstudiante.getEstudiantes()[i].getCedula(), i, 0);
            this.tabEstudiantes.setValueAt(gEstudiante.getEstudiantes()[i].getCedula(), i, 0);
            this.tabEstudiantes.setValueAt(gEstudiante.getEstudiantes()[i].getNombre(), i, 1);
            this.tabEstudiantes.setValueAt(gEstudiante.getEstudiantes()[i].getApellido(), i, 2);
            this.tabEstudiantes.setValueAt(gEstudiante.getEstudiantes()[i].getEdad(), i, 3);
            this.tabEstudiantes.setValueAt(gEstudiante.getEstudiantes()[i].getNota1(), i, 4);
            this.tabEstudiantes.setValueAt(gEstudiante.getEstudiantes()[i].getNota2(), i, 5);
            this.tabEstudiantes.setValueAt(gEstudiante.getEstudiantes()[i].getNota3(), i, 6);
            this.tabEstudiantes.setValueAt(gEstudiante.getEstudiantes()[i].getPromedio(), i, 7);
            this.tabEstudiantes.setValueAt(gEstudiante.getEstudiantes()[i].getEstado(), i, 8);
        }
    }
     

    
    
    public void llenarDatosTabla() {
        int numEstudiantes = gEstudiante.getNumEstudiantes();
        for(int i = 0; i < numEstudiantes; i++){
            this.tabEstudiantes.setValueAt(gEstudiante.getEstudiantes()[i].getCedula(), i, 0);
            this.tabEstudiantes.setValueAt(gEstudiante.getEstudiantes()[i].getNombre(), i, 1);
            this.tabEstudiantes.setValueAt(gEstudiante.getEstudiantes()[i].getApellido(), i, 2);
            this.tabEstudiantes.setValueAt(gEstudiante.getEstudiantes()[i].getEdad(), i, 3);
            this.tabEstudiantes.setValueAt(gEstudiante.getEstudiantes()[i].getNota1(), i, 4);
            this.tabEstudiantes.setValueAt(gEstudiante.getEstudiantes()[i].getNota2(), i, 5);
            this.tabEstudiantes.setValueAt(gEstudiante.getEstudiantes()[i].getNota3(), i, 6);
            this.tabEstudiantes.setValueAt(gEstudiante.getEstudiantes()[i].getPromedio(), i, 7);
            this.tabEstudiantes.setValueAt(gEstudiante.getEstudiantes()[i].getEstado(), i, 8);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btAceptar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabEstudiantes = new javax.swing.JTable();
        btBuscar = new javax.swing.JButton();
        txtClaveBusqueda = new javax.swing.JTextField();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        btAceptar.setText("Aceptar");
        btAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAceptarActionPerformed(evt);
            }
        });

        tabEstudiantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Cedula", "Nombre", "Apellido", "Edad", "Nota 1", "Nota 2", "Nota 3", "Promedio", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tabEstudiantes);

        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        txtClaveBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClaveBusquedaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 813, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtClaveBusqueda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btBuscar)
                        .addGap(156, 156, 156)
                        .addComponent(btAceptar)
                        .addGap(375, 375, 375))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAceptar)
                    .addComponent(btBuscar)
                    .addComponent(txtClaveBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void btAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAceptarActionPerformed
        this.dispose();
        gEstudiante.guardarArchivo();
    }//GEN-LAST:event_btAceptarActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        busqueda(txtClaveBusqueda.getText());
        //mostrarDatos();
        if(txtClaveBusqueda.getText().isEmpty()){
            llenarDatosTabla();
        }
        else {
            borrarDatosTabla();
            mostrarCoincidencias();
        }
    }//GEN-LAST:event_btBuscarActionPerformed

    private void txtClaveBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClaveBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClaveBusquedaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                ventanaListarEstudiantes dialog = new ventanaListarEstudiantes(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAceptar;
    private javax.swing.JButton btBuscar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabEstudiantes;
    private javax.swing.JTextField txtClaveBusqueda;
    // End of variables declaration//GEN-END:variables
    public GestorEstudiante getEstudiante() {
        return gEstudiante;
    }

    public void setEstudiantes(GestorEstudiante estudiante) {
        this.gEstudiante = estudiante;
    }
}
